### PR TITLE
Time format update

### PR DESCRIPTION
**Pull request by RajChanchal**
Instead of showing hour as 00 when total time is not more than an hour, just show minutes and seconds

### CODE REVIEW

**Review by josejuanqm — CHANGES_REQUESTED** [review]
Awesome, thanks!

Could we remove the comment at line 25?

After this I can merge and upload a new version.

Thanks a lot!

**Comment by RajChanchal** [comment]
Just updated. :)

**Comment by RajChanchal** [comment]
Just updated. :)

**Review by josejuanqm — APPROVED** [review]

**Comment by josejuanqm** [comment]
I'll update the pod asap

**Pull request merged**
