### PR TITLE
Fix: NSNotification.Name.AVPlayerItemDidPlayToEndTime never arrive

### PR DESCRIPTION
**Pull request by pbeast**

### CODE REVIEW

**Comment by josejuanqm** [comment]
Thanks a lot!, merging now

**Comment by josejuanqm** [comment]
Will make it available today as 0.3.3

**Comment by josejuanqm** [comment]
Thank you @pbeast , version 0.3.3 has been made available. 

As a side note, you have been added to the contributors list at the readme page. Thank you for your support and for making VersaPlayer possible.

**Comment by pbeast** [comment]
👍

**Pull request merged**
