### PR TITLE
Enable double tap for fullscreen toggle

### PR DESCRIPTION
**Pull request by pbeast**

### CODE REVIEW

**Comment by josejuanqm** [comment]
Thanks @pbeast , I made a few modifications such as instead of fullscreen it changes the video gravity since double tap is natively attributed to that functionality.

Also commented the code because thats how docs are generated.

Thanks!

**Comment by pbeast** [comment]
Hi,

I know, your project - your rules :-) But your modification isn’t good for me (except comments part).
I’m working on video player for kids, and for such viewers video gravity is less important than ability to toggle fullscreen. Also, the pan gesture is very confusing even for me, nothing say about four years old.
What do you think about providing ability to override default gesture behaviour?

Regards,
Pavel Yankelevich

**Comment by josejuanqm** [comment]
Hi @pbeast,

It’s really awesome that you are using versa player in your projects, I appreciate your support and feedback.

There is a delegate called VersaPlayerGestureRecieverDelegate, inside VersaPlayerControlsCoordinator, you can set.

You can access this property like this:

```swift
...
playerView.controls?.controlsCoordinator.gestureReciever.delegate = newDelegate
```

Or set a custom reciever view when setting your player controls, like this:

```swift
...
playerView.use(controls, with: yourCustomRecieverView)
```

Again thanks for the awesome support, I appreciate it!

**Comment by pbeast** [comment]
Thanks. Added own delegate and that worked perfectly.
But what do you think about adding a shortcut to the delegate? Something like 
`playerView.gestureRecieverDelegate = newDelegate`

**Comment by josejuanqm** [comment]
Great!

I know it might look like a mess having it like that, but since not all players use controls and the coordinator only exists when adding controls, I didn't added there because I tried to keep it as low on optionals as possible on the main class.

**Pull request merged**
